' Project name:         Random Swap Project
' Project purpose:      Displays the lowest and highest of
'                       two random integers generated by the computer
' Created/revised by:   <your name> on <current date>

Option Explicit On
Option Strict On
Option Infer Off

Public Class MainForm

    Private Sub exitButton_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles exitButton.Click
        Me.Close()

    End Sub

End Class
